baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: "SPYDER ACADEMY"

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
   disableJS: true
   disableHTML: true


googleAnalytics: "G-FT7VJCMYJ5"
enableRobotsTXT: false

summaryLength: 20
paginate: 1000
params:
  title: "Spyder Academy | Beat The Market with AI Insights"
  description: "Spyder Academy provides education, data driven tools utilizing AI, and a social trading platform to help traders gain an edge trading the stock market."
  images: 
    - "images/whitelogo.png"

  logo: "blacklogo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://x.com/spyderacademy"
    instagram: "https://www.instagram.com/spyderacademy"
    pinterest: "https://www.pinterest.com/spyderacademy"
    substack: "https://spyderacademy.substack.com"
    
  shareButtons:
     size: small
     icon: solid
     networks:
        - facebook
        - twitter
        - pinterest
        
  copyright: "© 2024 SpyderAcademy, LLC"
  whop: "https://whop.com/checkout/plan_bCMjkbQ9TJsN2?d2c=true"
  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Education"
      url: "/courses/"
      weight: 2

    - name: "Trade Social"
      url: "/tradesocial/"
      weight: 3

    - name: "Earnings"
      url: "/tradesocial/earnings_calendar/"
      weight: 4

    - name: "Economic Calendar"
      url: "/tradesocial/economic_calendar/"
      weight: 5

    - name: "Profile"
      url: "/profile/"
      weight: 6

    - name: "🔎"
      url: "/search/"
      weight: 9

  buttons:
    # - name: "Start Learning"
    #   url: "https://whop.com/spyder-academy/?d2c=true&directPlanId=plan_2qHRKoIbGU6NN&pass=prod_45GZIGs1lRCGs&a=spyderacademy"
    #   weight: 5
    #   pre: "btn btn-primary text-light"

    - name: "Log in"
      url: "/login/"
      weight: 5
      pre: "btn gradient-green text-light"

    # - name: "Join The Beta"
    #   url: "https://whop.com/checkout/plan_bCMjkbQ9TJsN2?d2c=true"
    #   weight: 6
    #   pre: "btn gradient-red text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Pricing"
      url: "/#pricing"
      weight: 4

    - name: "Learn"
      url: "/courses/"
      weight: 5


    - name: "Timeline"
      url: "/tradesocial/"
      weight: 7

    - name: "Profile"
      url: "/profile/"
      weight: 8

    - name: "Other Tools"
      url: "/tools/"
      weight: 9

    - name: "Terms of Use"
      url: "/termsofuse/"
      weight: 10

    - name: "Privacy Policy"
      url: "/privacy/"
      weight: 11


taxonomies:
  tags: "tags"
