baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: "SPYDER ACADEMY"

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
   disableJS: true
   disableHTML: true


googleAnalytics: "G-FT7VJCMYJ5"
enableRobotsTXT: false

summaryLength: 20
paginate: 1000
params:
  title: "Spyder Academy | Learn How To Invest in Stocks and Options"
  description: "Spyder Academy specializes in providing education and training to beginner traders learning how to trade in the Stock Market. Work from Home or Learn a side hustle with our trading strategies and investment tips to help you gain financial freedom."
  images: 
    - "images/whitelogo.png"

  logo: "blacklogo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://x.com/spyderacademy"
    instagram: "https://www.instagram.com/spyderacademy"
    pinterest: "https://www.pinterest.com/spyderacademy"
    substack: "https://spyderacademy.substack.com"
    
  shareButtons:
     size: small
     icon: solid
     networks:
        - facebook
        - twitter
        - pinterest
        
  copyright: "© 2024 SpyderAcademy, LLC"
  whop: "https://whop.com/spyder-academy/?d2c=true&directPlanId=plan_2qHRKoIbGU6NN&pass=prod_45GZIGs1lRCGs&a=spyderacademy"
  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Education"
      url: "/courses/"
      weight: 5

    - name: "Trade Social"
      url: "/tradesocial/"
      weight: 7

    - name: "Profile"
      url: "/profile/"
      weight: 8

    - name: "🔎"
      url: "/search/"
      weight: 9

  buttons:
    # - name: "Start Learning"
    #   url: "https://whop.com/spyder-academy/?d2c=true&directPlanId=plan_2qHRKoIbGU6NN&pass=prod_45GZIGs1lRCGs&a=spyderacademy"
    #   weight: 5
    #   pre: "btn btn-primary text-light"

    - name: "Log in"
      url: "/login/"
      weight: 5
      pre: "btn gradient-green text-light"

    # - name: "Join The Beta"
    #   url: "https://whop.com/checkout/plan_bCMjkbQ9TJsN2?d2c=true"
    #   weight: 6
    #   pre: "btn gradient-red text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How We Teach"
      url: "/#mission"
      weight: 2

    - name: "Pricing"
      url: "/#services"
      weight: 4

    - name: "Education"
      url: "/education/"
      weight: 5

    - name: "Online Courses"
      url: "/courses/"
      weight: 6

    - name: "Trade Social"
      url: "/tradesocial/"
      weight: 7

    - name: "Profile"
      url: "/profile/"
      weight: 8

    - name: "Other Trading Tools"
      url: "/tools/"
      weight: 9

    - name: "Terms of Use"
      url: "/termsofuse/"
      weight: 9

    - name: "Privacy Policy"
      url: "/privacy/"
      weight: 10


taxonomies:
  tags: "tags"
