baseURL: ""
theme: "up-business-theme"
languageCode: "en-us"

title: "SPYDER ACADEMY"

markup:
  goldmark:
    renderer:
      unsafe: true


googleAnalytics: "G-FT7VJCMYJ5"

summaryLength: 20
paginate: 50
params:
  title: "Spyder Academy | Learn How To Invest in Stocks and Options"
  description: "Spyder Academy specializes in providing education and training to beginner traders learning how to trade in the Stock Market. Work from Home or Learn a side hustle with our trading strategies and investment tips to help you gain financial freedom."
  images: 
    - "images/whitelogo.png"

  logo: "blacklogo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://www.twitter.com/spyderacademy"
    instagram: "https://www.instagram.com/spyderacademy"
    pinterest: "https://www.pinterest.com/spyderacademy"
    
  shareButtons:
     size: small
     icon: solid
     networks:
        - facebook
        - twitter
        - pinterest
        
  copyright: "© 2023 SpyderAcademy, LLC"
  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Our Team"
      url: "/#teachers"
      weight: 3

    - name: "Pricing"
      url: "/#services"
      weight: 4

    - name: "Reviews"
      url: "/#testimonials"
      weight: 5

    - name: "Education"
      url: "/education"
      weight: 6

    - name: "Buy Us Coffee"
      url: "https://whop.com/checkout/plan_QiCwlm5hSTMgd/"
      weight: 6

  buttons:
    - name: "Start Learning"
      url: "/#services"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How We Teach"
      url: "/#mission"
      weight: 2

    - name: "Our Team"
      url: "/#teachers"
      weight: 3

    - name: "Pricing"
      url: "/#services"
      weight: 4

    - name: "Education"
      url: "/education"
      weight: 5

    - name: "Terms of Use"
      url: "/termsofuse"
      weight: 5

    - name: "Privacy Policy"
      url: "/privacy"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
